// Reading and phrasing "which model made this".
//
// Client-safe: this module knows about a two-field record the server put in an
// envelope's meta, and nothing about providers, credentials or resolution.
//
// It exists because the editors used to carry a hardcoded "Generated by
// DeepSeek" line. That was true only while nobody could change the provider;
// once a user can point Component Generation at their own connection, a
// compiled-in provider name becomes a confident wrong answer about who
// answered -- the same class of defect the model chooser's three-state status
// exists to prevent.
//
// The rule here is the same one: NEVER NAME A MODEL THAT HAS NOT ANSWERED.
// There is deliberately no way to derive a label from the user's current
// preference, because the preference is what WILL run, not what DID.

import type { AIGenerationAttribution } from './contracts';

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

/**
 * Pulls the attribution out of whatever the editor is holding -- a fresh
 * response, a saved envelope, legacy HTML, or nothing at all.
 *
 * Returns null for everything it cannot read, including every piece of content
 * generated before this was recorded. Null means "not known", and the caller
 * must render no claim rather than a default one.
 */
export function readAIGenerationAttribution(content: unknown): AIGenerationAttribution | null {
  if (!isRecord(content)) return null;
  const meta = content.meta;
  if (!isRecord(meta)) return null;
  const generatedBy = meta.generatedBy;
  if (!isRecord(generatedBy)) return null;

  const { source, model } = generatedBy;
  if (source !== 'collabboard-default' && source !== 'byok') return null;
  if (typeof model !== 'string' || !model.trim()) return null;

  return { source, model: model.trim() };
}

/**
 * The attribution line.
 *
 * The model id is shown verbatim because it is the only fully honest part: it
 * is exactly the string sent to the provider. The source half is named in the
 * user's own terms -- the same two names Settings uses -- rather than as a
 * provider brand, which this record does not carry and must not be guessed at
 * from a model id.
 */
export function formatAIGenerationAttribution(attribution: AIGenerationAttribution): string {
  const who = attribution.source === 'byok' ? 'your connection' : 'CollabBoard Default';
  return `Generated by ${who} · ${attribution.model}`;
}
