import { describe, expect, it } from 'vitest';

import { formatAIGenerationAttribution, readAIGenerationAttribution } from './attribution';

/**
 * THE RULE: never name a model that has not answered.
 *
 * The editors carried a hardcoded "Generated by DeepSeek" line, which was true
 * only while nobody could change the provider. Now that Component Generation is
 * a user-assignable role, a compiled-in name is a confident wrong answer -- the
 * same class of defect the model chooser's three-state status exists to stop.
 *
 * So the reader returns null for everything it cannot actually read, and null
 * must render as no claim at all rather than as a default.
 */

const VALID = { source: 'byok', model: 'gpt-4o' };

describe('reading the attribution off content in hand', () => {
  it('reads what the server reported', () => {
    expect(readAIGenerationAttribution({ meta: { generatedBy: VALID } }))
      .toEqual({ source: 'byok', model: 'gpt-4o' });
    expect(readAIGenerationAttribution({
      meta: { generatedBy: { source: 'collabboard-default', model: 'deepseek-flash' } },
    })).toEqual({ source: 'collabboard-default', model: 'deepseek-flash' });
  });

  it('content generated before this was recorded reads as NOT KNOWN, not as a default', () => {
    // Every saved card that predates this unit lands here. Answering
    // "CollabBoard Default" for them would be a guess dressed as a fact.
    expect(readAIGenerationAttribution({ mode: 'lesson_board', version: 1, data: {} })).toBeNull();
    expect(readAIGenerationAttribution({ meta: { prompt: 'p', createdAt: 'x' } })).toBeNull();
  });

  it('nothing, legacy HTML and junk all read as not known', () => {
    expect(readAIGenerationAttribution(null)).toBeNull();
    expect(readAIGenerationAttribution(undefined)).toBeNull();
    expect(readAIGenerationAttribution('a string')).toBeNull();
    expect(readAIGenerationAttribution({ html: '<p>legacy</p>' })).toBeNull();
    expect(readAIGenerationAttribution({ meta: 'not an object' })).toBeNull();
  });

  it('a malformed or unknown source is refused rather than shown', () => {
    // A stored card is persisted JSON a later version could have written
    // differently; an unrecognised source must not be rendered verbatim.
    expect(readAIGenerationAttribution({ meta: { generatedBy: { source: 'other', model: 'm' } } })).toBeNull();
    expect(readAIGenerationAttribution({ meta: { generatedBy: { source: 'byok' } } })).toBeNull();
    expect(readAIGenerationAttribution({ meta: { generatedBy: { source: 'byok', model: '   ' } } })).toBeNull();
    expect(readAIGenerationAttribution({ meta: { generatedBy: { source: 'byok', model: 7 } } })).toBeNull();
  });

  it('reads ONLY the two fields, so a key stored beside them could never be read out', () => {
    const read = readAIGenerationAttribution({
      meta: { generatedBy: { source: 'byok', model: 'gpt-4o', apiKey: 'SECRET-KEY-XYZ' } },
    });
    expect(Object.keys(read!).sort()).toEqual(['model', 'source']);
    expect(JSON.stringify(read)).not.toContain('SECRET-KEY-XYZ');
  });
});

describe('phrasing the attribution', () => {
  it('names the model verbatim -- it is the only fully honest part', () => {
    expect(formatAIGenerationAttribution({ source: 'byok', model: 'gpt-4o' }))
      .toBe('Generated by your connection · gpt-4o');
    expect(formatAIGenerationAttribution({ source: 'collabboard-default', model: 'deepseek-flash' }))
      .toBe('Generated by CollabBoard Default · deepseek-flash');
  });

  it('never names a provider brand, which this record does not carry', () => {
    // The old line said "DeepSeek" because the route did. Nothing here may
    // infer a provider from a model id -- gpt-4o does not say "OpenAI" to this
    // module, and guessing is how the previous defect worked.
    const line = formatAIGenerationAttribution({ source: 'byok', model: 'gpt-4o' });
    expect(line).not.toMatch(/OpenAI|Anthropic|Gemini|DeepSeek|OpenRouter/);
  });
});
