CREATE TABLE IF NOT EXISTS public.auth_rate_limit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action text NOT NULL CHECK (action IN ('login', 'password_reset')),
    email_hash text NOT NULL,
    ip_hash text NOT NULL,
    success boolean NOT NULL DEFAULT false,
    user_agent text,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS auth_rate_limit_events_action_created_at_idx
    ON public.auth_rate_limit_events (action, created_at DESC);

CREATE INDEX IF NOT EXISTS auth_rate_limit_events_email_hash_created_at_idx
    ON public.auth_rate_limit_events (email_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS auth_rate_limit_events_ip_hash_created_at_idx
    ON public.auth_rate_limit_events (ip_hash, created_at DESC);

ALTER TABLE public.auth_rate_limit_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.auth_rate_limit_events FROM anon;
REVOKE ALL ON public.auth_rate_limit_events FROM authenticated;
